const $=(s,p=document)=>p.querySelector(s);
const safe=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

function assetUrl(path){
  if(!path||!location.search.includes('eo_token=')) return path;
  return `${path}${path.includes('?')?'&':'?'}${location.search.slice(1)}`;
}
async function getJSON(path,fallback){try{const r=await fetch(assetUrl(path),{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
const messageTime=value=>new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));
const isHistory=w=>w.archiveGroup==='historical'||w.format==='SCANNED_DOCUMENT'||w.type==='历史档案';
const historyKind=w=>w.archiveMediaType||(w.format==='SCANNED_DOCUMENT'?'scans':w.mediaType==='video'?'video':'image');

async function loadMessages(){
  const list=$('#messageList');
  try{const r=await fetch(assetUrl('/api/messages'),{cache:'no-store'});if(!r.ok)throw new Error();const messages=await r.json();list.innerHTML=messages.length?messages.map(m=>`<article class="message-item"><div><strong>${safe(m.name)}</strong><time datetime="${safe(m.createdAt)}">${safe(messageTime(m.createdAt))}</time></div><p>${safe(m.message)}</p></article>`).join(''):'<p class="message-empty">还没有留言，成为第一个留下讯号的人。</p>'}catch{list.innerHTML='<p class="message-empty">留言频道暂时无法连接。</p>'}
}
function initMessages(){
  const form=$('#messageForm'),status=$('#messageStatus');
  form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;status.textContent='发送中…';try{const body={name:$('#messageName').value.trim(),message:$('#messageText').value.trim()};const r=await fetch(assetUrl('/api/messages'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||'发送失败');form.reset();status.textContent='留言已同步';await loadMessages()}catch(err){status.textContent=err.message||'发送失败，请稍后重试'}finally{button.disabled=false}});
  loadMessages();setInterval(loadMessages,30000);
}
function setImage(el,path,options={}){if(!path)return;const probe=new Image();probe.onload=()=>{el.style.backgroundImage=`url("${assetUrl(path)}")`;if(options.position)el.style.backgroundPosition=options.position;if(options.fit)el.style.backgroundSize=options.fit;$('.image-fallback',el)?.remove()};probe.src=assetUrl(path)}
function renderTarget(t){const timeline=(t.timeline||[]).map(x=>`<li><time>${safe(x.date)}</time><span>${safe(x.event)}</span></li>`).join('');const face=t.face||{x:50,y:40,width:36};return `<article class="target-card"><div class="target-visual" data-image="${safe(t.image)}" style="--face-x:${Number(face.x)||50};--face-y:${Number(face.y)||40};--face-w:${Number(face.width)||36}"><div class="target-placeholder"><span>NO VISUAL FEED</span></div><div class="yolo-box"><span>person ${safe(t.match||'TRACKED')}</span><i></i><b></b><em></em><u></u></div><div class="target-hud"><div><span>${safe(t.id)}</span><span>DETECTION // LIVE</span></div><div><span>OBJECT LOCKED</span><span class="match">CONF ${safe(t.match)}</span></div></div></div><div class="target-info"><span class="target-status">${safe(t.status)}</span><h3>${safe(t.name)}</h3><p class="eyebrow">${safe(t.role)}</p>${timeline?`<ol class="timeline">${timeline}</ol>`:''}</div></article>`}
function renderWork(w,i){const history=isHistory(w),kind=historyKind(w),cover=(w.content||[])[0]||w.image,count=kind==='scans'?`${(w.content||[]).length} SCANS`:kind.toUpperCase();return `<article class="work-card archive-file${history?' historical-archive':''}" tabindex="0" data-index="${i}"><div class="file-tab">${safe(w.id)} / ${safe(history?w.status||'DECRYPTED':'SEALED')}</div><div class="work-art" ${cover&&kind!=='video'?`style="background-image:url('${safe(assetUrl(cover))}');background-size:cover;background-position:top center"`:''}><span class="archive-stamp">${history?'DECRYPTED<br>DATA RECOVERED':'ARCHIVED<br>ACCESS LOGGED'}</span></div><div class="file-index"><span>${safe(w.id)}</span><span>${history?safe(count):'CLASSIFIED'}</span></div><h3>${safe(w.title)}</h3><span class="work-type">${safe(w.type)} / ${safe(w.author)}</span></article>`}
function openViewer(w){
  if(isHistory(w)){const kind=historyKind(w),pages=(w.content||[w.image]).filter(Boolean);let media='';if(kind==='video'){const src=assetUrl(w.image||pages[0]);media=`<div class="history-single"><video controls playsinline preload="metadata" src="${safe(src)}"></video></div>`}else if(kind==='image'){const src=assetUrl(w.image||pages[0]);media=`<div class="history-single"><img src="${safe(src)}" alt="${safe(w.title)}"></div>`}else{media=`<div class="scan-pages">${pages.map((src,i)=>`<figure><span>SCAN ${String(i+1).padStart(2,'0')} / ${String(pages.length).padStart(2,'0')}</span><img src="${safe(assetUrl(src))}" alt="${safe(w.title)} 第 ${i+1} 页" loading="${i?'lazy':'eager'}"></figure>`).join('')}</div>`}$('#viewerBody').innerHTML=`<div class="viewer-inner history-viewer"><header class="history-meta"><span class="eyebrow">${safe(w.id)} / ${safe(w.status||'DECRYPTED')} / ${safe(kind.toUpperCase())}</span><h2>${safe(w.title)}</h2><span class="work-type">${safe(w.type)} / ${safe(w.author)}</span></header>${media}</div>`
  }else{const src=assetUrl(w.image);const media=w.mediaType==='video'&&src?`<div class="viewer-art"><video controls playsinline src="${safe(src)}"></video></div>`:`<div class="viewer-art" ${src?`style="background-image:url('${safe(src)}');background-size:contain;background-repeat:no-repeat;background-position:center"`:''}><span>${safe(w.id)} / SEALED FILE</span></div>`;$('#viewerBody').innerHTML=`<div class="viewer-inner">${media}<div class="viewer-copy"><span class="eyebrow">${safe(w.id)} / CLASSIFIED / ${safe(w.type)}</span><h2>${safe(w.title)}</h2><span class="work-type">ARCHIVED BY: ${safe(w.author)}</span></div></div>`}
  $('#viewer').showModal();
}
async function boot(){
  const [staticSubjects,staticWorks,staticLayout,cloud]=await Promise.all([getJSON('/data/subjects.json',[]),getJSON('/data/works.json',[]),getJSON('/data/layout.json',{}),getJSON('/api/content',null)]);
  const subjects=cloud?.subjects||staticSubjects,layout=cloud?.layout||staticLayout;
  const works=cloud?.works?[...cloud.works]:[...staticWorks];for(const item of staticWorks.filter(isHistory)){if(!works.some(w=>w.id===item.id))works.push(item)}
  document.body.dataset.worksMode=layout.worksMode||'rail';document.body.dataset.cardRatio=layout.cardRatio||'portrait';document.body.dataset.accent=layout.accent||'violet';document.body.dataset.heroMode=layout.heroMode||'split';
  if(layout.intro)$('.lede').textContent=layout.intro;const headline=String(layout.headline||'DAVIS\nPRIVATE NODE').split('\n');$('#heroHeadline').innerHTML=`${safe(headline[0]||'DAVIS')}<br><i>${safe(headline.slice(1).join(' ')||'PRIVATE NODE')}</i>`;
  const davis=subjects.find(x=>x.id==='OPERATOR_00');if(davis){const hero=$('#heroImage');hero.style.setProperty('--hero-overlay',String((layout.heroOverlay??35)/100));setImage(hero,davis.image,{position:`${layout.heroX??50}% ${layout.heroY??50}%`,fit:layout.heroFit||'cover'});setImage($('#profileImage'),davis.profileImage)}
  $('#targetGrid').innerHTML=subjects.filter(x=>x.id.startsWith('TARGET_')).map(renderTarget).join('');document.querySelectorAll('.target-visual[data-image]').forEach(el=>setImage(el,el.dataset.image));
  const current=works.filter(w=>!isHistory(w)),historical=works.filter(isHistory);$('#workTrack').innerHTML=current.map(renderWork).join('');$('#historyTrack').innerHTML=historical.map(renderWork).join('');document.querySelectorAll('#workTrack .work-card').forEach(c=>{const open=()=>openViewer(current[+c.dataset.index]);c.onclick=open;c.onkeydown=e=>{if(e.key==='Enter')open()}});document.querySelectorAll('#historyTrack .work-card').forEach(c=>{const open=()=>openViewer(historical[+c.dataset.index]);c.onclick=open;c.onkeydown=e=>{if(e.key==='Enter')open()}});
}
$('.close').onclick=()=>$('#viewer').close();boot();initMessages();
