let data,key='';const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function apiUrl(path){if(!location.search.includes('eo_token='))return path;return `${path}${path.includes('?')?'&':'?'}${location.search.slice(1)}`}
const clone=x=>JSON.parse(JSON.stringify(x));
const history=w=>w.archiveGroup==='historical'||w.format==='SCANNED_DOCUMENT'||w.type==='历史档案';
const historyKind=w=>w.archiveMediaType||(w.format==='SCANNED_DOCUMENT'?'scans':w.mediaType==='video'?'video':'image');
async function getData(){try{const r=await fetch(apiUrl('/api/content'),{cache:'no-store'}),x=await r.json();return x||clone(SEED)}catch{return clone(SEED)}}

$('#unlock').onclick=async()=>{key=$('#key').value.trim();$('#loginMsg').textContent='验证中…';try{const r=await fetch(apiUrl('/api/auth'),{method:'POST',headers:{'x-admin-key':key}});if(!r.ok)throw new Error('管理密码错误');data=await getData();data.layout||={};data.subjects||=[];data.works||=[];$('#login').hidden=true;$('#editor').hidden=false;$('#savebar').hidden=false;bind();draw()}catch(e){$('#loginMsg').textContent=e.message||'暂时无法登录'}};
$('#key').onkeydown=e=>{if(e.key==='Enter')$('#unlock').click()};
function bind(){for(const id of ['headline','intro','worksMode','accent','heroX','heroY']){const el=$('#'+id);el.value=data.layout[id]??(id==='heroY'?50:'');el.oninput=()=>{data.layout[id]=['heroX','heroY'].includes(id)?+el.value:el.value;if(id.startsWith('hero'))$('#'+id+'Out').textContent=el.value+'%'}}$('#heroXOut').textContent=(data.layout.heroX??50)+'%';$('#heroYOut').textContent=(data.layout.heroY??50)+'%'}
async function uploadFile(file){
  if(file.size>25*1024*1024)throw new Error('单个文件不能超过 25MB');
  if(file.size<=8*1024*1024){const direct=await fetch(apiUrl('/api/upload'),{method:'PUT',headers:{'content-type':file.type,'x-admin-key':key},body:file});const saved=await direct.json().catch(()=>({}));if(!direct.ok)throw new Error(saved.error||`图片上传失败（${direct.status}）`);return saved.publicUrl}
  const r=await fetch(apiUrl('/api/upload'),{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify({name:file.name,contentType:file.type})}),j=await r.json();if(!r.ok)throw new Error(j.error||'无法创建上传');
  let put;try{put=await fetch(j.url,{method:'PUT',headers:{'content-type':file.type||'application/octet-stream'},body:file})}catch{throw new Error('上传连接失败，请切换网络后重试')}if(!put.ok)throw new Error(`文件上传失败（${put.status}）`);return j.publicUrl;
}
async function uploadMany(files,onDone){const list=[...files];if(!list.length)return;$('#msg').textContent=`UPLOADING 0 / ${list.length}`;const urls=[];for(let i=0;i<list.length;i++){urls.push(await uploadFile(list[i]));$('#msg').textContent=`UPLOADING ${i+1} / ${list.length}`}onDone(urls);$('#msg').textContent='上传完成，请保存';draw()}
function draw(){
  $('#subjects').innerHTML=data.subjects.map((s,i)=>`<article class="edit"><div class="photo" style="background-image:url('${esc(apiUrl(s.image))}')"></div><h3>${esc(s.name)}</h3><label class="upload">更换照片<input data-subject="${i}" type="file" accept="image/*"></label>${s.id==='OPERATOR_00'?`<label class="upload">更换档案头像<input data-profile="${i}" type="file" accept="image/*"></label>`:`<div class="ranges">${['x','y','width'].map(f=>`<label>${f==='x'?'左右':f==='y'?'上下':'大小'} ${s.face?.[f]??40}%<input data-face="${i}:${f}" type="range" min="${f==='width'?15:5}" max="${f==='width'?70:95}" value="${s.face?.[f]??40}"></label>`).join('')}</div>`}</article>`).join('');
  $('#works').innerHTML=data.works.map((w,i)=>{const h=history(w),kind=historyKind(w),pages=w.content||[];const historyMedia=kind==='scans'?`<label class="upload wide">追加扫描页<input data-historyfiles="${i}" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div class="scanList wide">${pages.length?pages.map((p,n)=>`<div><img src="${esc(apiUrl(p))}" alt="第${n+1}页"><span>SCAN ${String(n+1).padStart(2,'0')}</span><button type="button" data-delpage="${i}:${n}">删除页</button></div>`).join(''):'<p>尚未上传扫描页</p>'}</div>`:`<label class="upload wide">上传${kind==='video'?'视频':'图片'}<input data-historysingle="${i}" type="file" accept="${kind==='video'?'video/mp4,video/quicktime,video/webm':'image/jpeg,image/png,image/webp'}"></label>${w.image?`<p class="wide uploadedFile">已上传：${esc(w.image.split('/').pop())}</p>`:''}`;return `<article class="workEdit${h?' historyEdit':''}"><b>${String(i+1).padStart(2,'0')}</b><div class="workFields"><label>标题<input data-work="${i}:title" value="${esc(w.title)}"></label><label>创作者<input data-work="${i}:author" value="${esc(w.author)}"></label><label>类型<input data-work="${i}:type" value="${esc(w.type)}"></label><label>贡献者<input data-work="${i}:contributor" value="${esc(w.contributor)}"></label>${h?`<label>状态<input data-work="${i}:status" value="${esc(w.status||'DECRYPTED')}"></label><label>档案格式<select data-historytype="${i}"><option value="scans" ${kind==='scans'?'selected':''}>多页扫描件</option><option value="image" ${kind==='image'?'selected':''}>图片</option><option value="video" ${kind==='video'?'selected':''}>视频</option></select></label>${historyMedia}`:`<label class="upload wide">上传封面 / 视频<input data-workfile="${i}" type="file" accept="image/*,video/*"></label>`}</div><aside><button type="button" data-up="${i}" aria-label="上移">↑</button><button type="button" data-down="${i}" aria-label="下移">↓</button><button type="button" data-del="${i}" aria-label="删除">×</button></aside></article>`}).join('');
  document.querySelectorAll('[data-subject],[data-profile],[data-workfile]').forEach(el=>el.onchange=async e=>{const file=e.target.files[0];if(!file)return;try{await uploadMany([file],urls=>{const si=el.dataset.subject,pi=el.dataset.profile,wi=el.dataset.workfile;if(si!=null)data.subjects[si].image=urls[0];if(pi!=null)data.subjects[pi].profileImage=urls[0];if(wi!=null){data.works[wi].image=urls[0];data.works[wi].mediaType=file.type.startsWith('video/')?'video':'image'}})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-historyfiles]').forEach(el=>el.onchange=async e=>{const i=+el.dataset.historyfiles;try{await uploadMany(e.target.files,urls=>{data.works[i].content=[...(data.works[i].content||[]),...urls];data.works[i].image=data.works[i].content[0]||''})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-historysingle]').forEach(el=>el.onchange=async e=>{const i=+el.dataset.historysingle,file=e.target.files[0];if(!file)return;try{await uploadMany([file],urls=>{data.works[i].image=urls[0];data.works[i].content=[];data.works[i].mediaType=historyKind(data.works[i])==='video'?'video':'image'})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-historytype]').forEach(el=>el.onchange=()=>{const i=+el.dataset.historytype;data.works[i].archiveMediaType=el.value;data.works[i].format=el.value==='scans'?'SCANNED_DOCUMENT':el.value==='video'?'VIDEO':'IMAGE';data.works[i].mediaType=el.value==='video'?'video':'image';data.works[i].content=[];data.works[i].image='';draw()});
  document.querySelectorAll('[data-face]').forEach(el=>el.oninput=()=>{const[i,f]=el.dataset.face.split(':');data.subjects[i].face||={};data.subjects[i].face[f]=+el.value});
  document.querySelectorAll('[data-work]').forEach(el=>el.oninput=()=>{const[i,f]=el.dataset.work.split(':');data.works[i][f]=el.value});
  document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=+b.dataset.up;if(i)[data.works[i-1],data.works[i]]=[data.works[i],data.works[i-1]];draw()});document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{const i=+b.dataset.down;if(i<data.works.length-1)[data.works[i+1],data.works[i]]=[data.works[i],data.works[i+1]];draw()});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('确定删除这项作品？')){data.works.splice(+b.dataset.del,1);draw()}});document.querySelectorAll('[data-delpage]').forEach(b=>b.onclick=()=>{const[i,n]=b.dataset.delpage.split(':').map(Number);data.works[i].content.splice(n,1);data.works[i].image=data.works[i].content[0]||'';draw()});
}
function nextId(prefix){const used=data.works.map(w=>w.id);let n=1,id;do{id=`${prefix}_${String(n++).padStart(3,'0')}`}while(used.includes(id));return id}
$('#add').onclick=()=>{data.works.push({id:nextId('FILE'),contributor:'',title:'NEW FILE',author:'',type:'作品',image:''});draw()};
$('#addHistory').onclick=()=>{data.works.push({id:nextId('ARCHIVE_HIST'),contributor:'',title:'NEW HISTORICAL FILE',author:'',type:'历史档案',archiveGroup:'historical',archiveMediaType:'scans',format:'SCANNED_DOCUMENT',targets:['TARGET_01','TARGET_02'],status:'DECRYPTED',tags:['数据恢复'],image:'',content:[]});draw()};
$('#save').onclick=async()=>{$('#msg').textContent='SAVING…';try{const r=await fetch(apiUrl('/api/content'),{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify(data)});if(!r.ok)throw new Error('保存失败');$('#msg').textContent='公开网页已更新 ✓'}catch(e){$('#msg').textContent=e.message||'保存失败'}};
