let data,key='';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function apiUrl(path){if(!location.search.includes('eo_token='))return path;const url=new URL(path,location.origin);for(const[k,v]of new URLSearchParams(location.search))url.searchParams.set(k,v);return url.toString()}
const clone=x=>JSON.parse(JSON.stringify(x));
const history=w=>w.archiveGroup==='historical'||w.type==='历史档案';
const archiveKind=w=>w.archiveMediaType||(w.mediaType==='video'?'video':(w.content||[]).length?'scans':'image');
const videoUrl=w=>w.media||(w.mediaType==='video'?w.image:'');
const defaultSections=()=>[
  {id:'current',title:'本次作品档案',eyebrow:'CURRENT CREATION FILES'},
  {id:'historical',title:'历史档案',eyebrow:'RECOVERED LEGACY MATERIAL'},
  {id:'images',title:'图片档案',eyebrow:'IMAGE ARCHIVE'},
  {id:'photos',title:'照片档案',eyebrow:'PHOTO ARCHIVE'},
  {id:'videos',title:'视频档案',eyebrow:'VIDEO ARCHIVE'},
  {id:'art',title:'绘画档案',eyebrow:'ART ARCHIVE'}
];
function normalizeSections(){data.sections=Array.isArray(data.sections)&&data.sections.length?data.sections:defaultSections();for(const w of data.works){if(!w.sectionId)w.sectionId=history(w)?'historical':'current';if(!data.sections.some(s=>s.id===w.sectionId))w.sectionId=data.sections[0].id}}
async function getData(){try{const r=await fetch(apiUrl('/api/content'),{cache:'no-store'}),x=await r.json();return x||clone(SEED)}catch{return clone(SEED)}}

$('#unlock').onclick=async()=>{key=$('#key').value.trim();$('#loginMsg').textContent='验证中…';try{const r=await fetch(apiUrl('/api/auth'),{method:'POST',headers:{'x-admin-key':key}});if(!r.ok)throw new Error('管理密码错误');data=await getData();data.layout||={};data.subjects||=[];data.works||=[];normalizeSections();$('#login').hidden=true;$('#editor').hidden=false;$('#savebar').hidden=false;bind();draw()}catch(e){$('#loginMsg').textContent=e.message||'暂时无法登录'}};
$('#key').onkeydown=e=>{if(e.key==='Enter')$('#unlock').click()};
function bind(){for(const id of ['headline','intro','worksMode','accent','heroX','heroY']){const el=$('#'+id);el.value=data.layout[id]??(id==='heroY'?50:'');el.oninput=()=>{data.layout[id]=['heroX','heroY'].includes(id)?+el.value:el.value;if(id.startsWith('hero'))$('#'+id+'Out').textContent=el.value+'%'}}$('#heroXOut').textContent=(data.layout.heroX??50)+'%';$('#heroYOut').textContent=(data.layout.heroY??50)+'%'}
async function uploadFile(file){
  const type=file.type||({'jpg':'image/jpeg','jpeg':'image/jpeg','png':'image/png','webp':'image/webp','gif':'image/gif','mp4':'video/mp4','mov':'video/quicktime','webm':'video/webm'}[file.name.split('.').pop().toLowerCase()]||'');
  if(!type)throw new Error('无法识别文件格式');if(file.size>100*1024*1024)throw new Error('单个文件不能超过 100MB');
  if(file.size<=4*1024*1024){const direct=await fetch(apiUrl('/api/upload'),{method:'PUT',headers:{'content-type':type,'x-admin-key':key},body:file});const saved=await direct.json().catch(()=>({}));if(!direct.ok)throw new Error(saved.error||`上传失败（${direct.status}）`);return saved.publicUrl}
  const start=await fetch(apiUrl('/api/upload'),{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify({mode:'start',name:file.name,contentType:type,size:file.size})}),session=await start.json().catch(()=>({}));if(!start.ok)throw new Error(session.error||'无法开始上传');
  const chunkSize=4*1024*1024,parts=Math.ceil(file.size/chunkSize);for(let i=0;i<parts;i++){const chunk=file.slice(i*chunkSize,Math.min((i+1)*chunkSize,file.size));const part=await fetch(apiUrl(`/api/upload?uploadId=${encodeURIComponent(session.uploadId)}&part=${i}`),{method:'PUT',headers:{'content-type':'application/octet-stream','x-admin-key':key},body:chunk});if(!part.ok){const error=await part.json().catch(()=>({}));throw new Error(error.error||`上传第 ${i+1} 段失败`)}$('#msg').textContent=`UPLOADING ${i+1} / ${parts}`}
  const finish=await fetch(apiUrl('/api/upload'),{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify({mode:'complete',uploadId:session.uploadId,name:file.name,contentType:type,size:file.size,parts})}),saved=await finish.json().catch(()=>({}));if(!finish.ok)throw new Error(saved.error||'合并文件失败');return saved.publicUrl;
}
async function uploadMany(files,onDone){const list=[...files];if(!list.length)return;$('#msg').textContent=`UPLOADING 0 / ${list.length}`;const urls=[];for(let i=0;i<list.length;i++){urls.push(await uploadFile(list[i]));$('#msg').textContent=`UPLOADING ${i+1} / ${list.length}`}onDone(urls);$('#msg').textContent='上传完成，请保存';draw()}
function mediaEditor(w,i){const kind=archiveKind(w),pages=w.content||[];
  if(kind==='scans')return `<label class="upload wide">追加扫描页 / 图片<input data-pages="${i}" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div class="scanList wide">${pages.length?pages.map((p,n)=>`<div><img src="${esc(apiUrl(p))}" alt="第${n+1}页"><span>SCAN ${String(n+1).padStart(2,'0')}</span><button type="button" data-delpage="${i}:${n}">删除页</button></div>`).join(''):'<p>尚未上传扫描页</p>'}</div>`;
  if(kind==='video')return `<label class="upload wide">上传 / 更换视频<input data-video="${i}" type="file" accept="video/mp4,video/quicktime,video/webm"></label><label class="upload wide coverUpload">上传 / 更换预览封面<input data-cover="${i}" type="file" accept="image/jpeg,image/png,image/webp"></label>${videoUrl(w)?`<p class="wide uploadedFile">视频已上传</p>`:''}${w.cover?`<div class="coverPreview wide"><img src="${esc(apiUrl(w.cover))}" alt="视频封面"><span>当前预览封面</span></div>`:'<p class="wide uploadedFile">尚未上传预览封面</p>'}`;
  return `<label class="upload wide">上传 / 更换图片<input data-image="${i}" type="file" accept="image/jpeg,image/png,image/webp"></label>${w.image?`<div class="coverPreview wide"><img src="${esc(apiUrl(w.image))}" alt="作品图片"><span>当前图片</span></div>`:''}`;
}
function subjectEditor(s,i){const operator=s.id==='OPERATOR_00',timeline=s.timeline||[];return `<article class="edit subjectEdit"><div class="photo" style="background-image:url('${esc(apiUrl(s.image))}')"></div><div class="subjectFields"><label>人物编号<input data-person="${i}:id" value="${esc(s.id)}" ${operator?'readonly':''}></label><label>姓名<input data-person="${i}:name" value="${esc(s.name)}"></label><label>身份<input data-person="${i}:role" value="${esc(s.role)}"></label><label>状态<input data-person="${i}:status" value="${esc(s.status)}"></label>${operator?`<label>权限<input data-person="${i}:access" value="${esc(s.access||'ROOT ACCESS')}"></label>`:`<label>匹配率<input data-person="${i}:match" value="${esc(s.match||'98.0%')}"></label>`}</div><label class="upload">更换人物照片<input data-subject="${i}" type="file" accept="image/*"></label>${operator?`<label class="upload">更换档案头像<input data-profile="${i}" type="file" accept="image/*"></label>`:`<div class="ranges">${['x','y','width'].map(f=>`<label>${f==='x'?'识别框左右':f==='y'?'识别框上下':'识别框大小'} ${s.face?.[f]??40}%<input data-face="${i}:${f}" type="range" min="${f==='width'?15:5}" max="${f==='width'?70:95}" value="${s.face?.[f]??40}"></label>`).join('')}</div><div class="timelineEditor"><strong>生平时间线</strong>${timeline.map((t,n)=>`<div><input data-life="${i}:${n}:date" value="${esc(t.date)}" placeholder="年份"><input data-life="${i}:${n}:event" value="${esc(t.event)}" placeholder="经历"><button type="button" data-dellife="${i}:${n}" aria-label="删除经历">×</button></div>`).join('')}<button type="button" data-addlife="${i}">＋ 添加经历</button></div><div class="subjectActions"><button type="button" data-subup="${i}">↑ 上移</button><button type="button" data-subdown="${i}">↓ 下移</button><button type="button" data-delsub="${i}">删除人物</button></div>`}</article>`}
function draw(){
  $('#subjects').innerHTML=data.subjects.map(subjectEditor).join('');
  $('#archiveSections').innerHTML=data.sections.map((s,i)=>`<article class="sectionEdit"><b>${String(i+1).padStart(2,'0')}</b><label>分栏名称<input data-section="${i}:title" value="${esc(s.title)}"></label><label>英文标记<input data-section="${i}:eyebrow" value="${esc(s.eyebrow||'CLASSIFIED ARCHIVE')}"></label><div><button type="button" data-sectionup="${i}">↑</button><button type="button" data-sectiondown="${i}">↓</button><button type="button" data-delsection="${i}">删除</button></div></article>`).join('');
  const sectionOptions=w=>data.sections.map(s=>`<option value="${esc(s.id)}" ${w.sectionId===s.id?'selected':''}>${esc(s.title)}</option>`).join('');
  $('#works').innerHTML=data.works.map((w,i)=>{const h=history(w),kind=archiveKind(w);return `<article class="workEdit${h?' historyEdit':''}"><b>${String(i+1).padStart(2,'0')}</b><div class="workFields"><label>所属分栏<select data-worksection="${i}">${sectionOptions(w)}</select></label><label>标题<input data-work="${i}:title" value="${esc(w.title)}"></label><label>创作者<input data-work="${i}:author" value="${esc(w.author)}"></label><label>类型<input data-work="${i}:type" value="${esc(w.type)}"></label><label>贡献者<input data-work="${i}:contributor" value="${esc(w.contributor)}"></label>${h?`<label>状态<input data-work="${i}:status" value="${esc(w.status||'DECRYPTED')}"></label>`:''}<label>档案内容<select data-mediatype="${i}"><option value="scans" ${kind==='scans'?'selected':''}>多页扫描件 / 图片组</option><option value="image" ${kind==='image'?'selected':''}>单张图片</option><option value="video" ${kind==='video'?'selected':''}>视频 + 预览封面</option></select></label>${mediaEditor(w,i)}</div><aside><button type="button" data-up="${i}" aria-label="上移">↑</button><button type="button" data-down="${i}" aria-label="下移">↓</button><button type="button" data-del="${i}" aria-label="删除">×</button></aside></article>`}).join('');
  document.querySelectorAll('[data-subject],[data-profile]').forEach(el=>el.onchange=async e=>{const file=e.target.files[0];if(!file)return;try{await uploadMany([file],urls=>{if(el.dataset.subject!=null)data.subjects[el.dataset.subject].image=urls[0];if(el.dataset.profile!=null)data.subjects[el.dataset.profile].profileImage=urls[0]})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-pages]').forEach(el=>el.onchange=async e=>{const i=+el.dataset.pages;try{await uploadMany(e.target.files,urls=>{data.works[i].content=[...(data.works[i].content||[]),...urls];data.works[i].image=data.works[i].content[0]||''})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-image]').forEach(el=>el.onchange=async e=>{const i=+el.dataset.image,file=e.target.files[0];if(!file)return;try{await uploadMany([file],urls=>{data.works[i].image=urls[0];data.works[i].media='';data.works[i].content=[];data.works[i].mediaType='image'})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-video]').forEach(el=>el.onchange=async e=>{const i=+el.dataset.video,file=e.target.files[0];if(!file)return;try{await uploadMany([file],urls=>{data.works[i].media=urls[0];data.works[i].mediaType='video';data.works[i].content=[]})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-cover]').forEach(el=>el.onchange=async e=>{const i=+el.dataset.cover,file=e.target.files[0];if(!file)return;try{await uploadMany([file],urls=>{data.works[i].cover=urls[0]})}catch(x){$('#msg').textContent=x.message}});
  document.querySelectorAll('[data-mediatype]').forEach(el=>el.onchange=()=>{const i=+el.dataset.mediatype,w=data.works[i];w.archiveMediaType=el.value;w.format=el.value==='scans'?'SCANNED_DOCUMENT':el.value==='video'?'VIDEO':'IMAGE';w.mediaType=el.value==='video'?'video':'image';w.content=[];w.image='';w.media='';w.cover='';draw()});
  document.querySelectorAll('[data-face]').forEach(el=>el.oninput=()=>{const[i,f]=el.dataset.face.split(':');data.subjects[i].face||={};data.subjects[i].face[f]=+el.value});
  document.querySelectorAll('[data-person]').forEach(el=>el.oninput=()=>{const[i,f]=el.dataset.person.split(':');data.subjects[i][f]=el.value});
  document.querySelectorAll('[data-life]').forEach(el=>el.oninput=()=>{const[i,n,f]=el.dataset.life.split(':');data.subjects[i].timeline[n][f]=el.value});
  document.querySelectorAll('[data-addlife]').forEach(b=>b.onclick=()=>{const s=data.subjects[+b.dataset.addlife];s.timeline||=[];s.timeline.push({date:'',event:''});draw()});
  document.querySelectorAll('[data-dellife]').forEach(b=>b.onclick=()=>{const[i,n]=b.dataset.dellife.split(':').map(Number);data.subjects[i].timeline.splice(n,1);draw()});
  document.querySelectorAll('[data-subup]').forEach(b=>b.onclick=()=>{const i=+b.dataset.subup;if(i>1)[data.subjects[i-1],data.subjects[i]]=[data.subjects[i],data.subjects[i-1]];draw()});
  document.querySelectorAll('[data-subdown]').forEach(b=>b.onclick=()=>{const i=+b.dataset.subdown;if(i<data.subjects.length-1)[data.subjects[i+1],data.subjects[i]]=[data.subjects[i],data.subjects[i+1]];draw()});
  document.querySelectorAll('[data-delsub]').forEach(b=>b.onclick=()=>{if(confirm('确定删除这个人物档案？')){data.subjects.splice(+b.dataset.delsub,1);draw()}});
  document.querySelectorAll('[data-work]').forEach(el=>el.oninput=()=>{const[i,f]=el.dataset.work.split(':');data.works[i][f]=el.value});
  document.querySelectorAll('[data-worksection]').forEach(el=>el.onchange=()=>{data.works[+el.dataset.worksection].sectionId=el.value});
  document.querySelectorAll('[data-section]').forEach(el=>el.oninput=()=>{const[i,f]=el.dataset.section.split(':');data.sections[i][f]=el.value});
  document.querySelectorAll('[data-sectionup]').forEach(b=>b.onclick=()=>{const i=+b.dataset.sectionup;if(i)[data.sections[i-1],data.sections[i]]=[data.sections[i],data.sections[i-1]];draw()});
  document.querySelectorAll('[data-sectiondown]').forEach(b=>b.onclick=()=>{const i=+b.dataset.sectiondown;if(i<data.sections.length-1)[data.sections[i+1],data.sections[i]]=[data.sections[i],data.sections[i+1]];draw()});
  document.querySelectorAll('[data-delsection]').forEach(b=>b.onclick=()=>{const i=+b.dataset.delsection;if(data.sections.length===1){$('#msg').textContent='至少保留一个档案分栏';return}if(confirm('删除这个分栏？其中作品会移入第一栏，不会被删除。')){const removed=data.sections[i].id,target=data.sections.find((_,n)=>n!==i).id;data.works.filter(w=>w.sectionId===removed).forEach(w=>w.sectionId=target);data.sections.splice(i,1);draw()}});
  document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=+b.dataset.up;if(i)[data.works[i-1],data.works[i]]=[data.works[i],data.works[i-1]];draw()});document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{const i=+b.dataset.down;if(i<data.works.length-1)[data.works[i+1],data.works[i]]=[data.works[i],data.works[i+1]];draw()});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('确定删除这项作品？')){data.works.splice(+b.dataset.del,1);draw()}});document.querySelectorAll('[data-delpage]').forEach(b=>b.onclick=()=>{const[i,n]=b.dataset.delpage.split(':').map(Number);data.works[i].content.splice(n,1);data.works[i].image=data.works[i].content[0]||'';draw()});
}
function nextId(prefix){const used=data.works.map(w=>w.id);let n=1,id;do{id=`${prefix}_${String(n++).padStart(3,'0')}`}while(used.includes(id));return id}
function nextSubjectId(){const used=data.subjects.map(s=>s.id);let n=1,id;do{id=`TARGET_${String(n++).padStart(2,'0')}`}while(used.includes(id));return id}
function nextSectionId(){const used=data.sections.map(s=>s.id);let n=1,id;do{id=`archive-${n++}`}while(used.includes(id));return id}
$('#addSubject').onclick=()=>{data.subjects.push({id:nextSubjectId(),name:'NEW TARGET',role:'INVESTIGATION TARGET',status:'TRACKING ACTIVE',match:'98.0%',image:'',timeline:[],face:{x:50,y:40,width:36}});draw()};
$('#addSection').onclick=()=>{data.sections.push({id:nextSectionId(),title:'新档案分栏',eyebrow:'CLASSIFIED ARCHIVE'});draw()};
$('#add').onclick=()=>{data.works.push({id:nextId('FILE'),sectionId:data.sections[0].id,contributor:'',title:'NEW FILE',author:'',type:'作品',archiveMediaType:'scans',format:'SCANNED_DOCUMENT',mediaType:'image',image:'',content:[]});draw()};
$('#save').onclick=async()=>{$('#msg').textContent='SAVING…';try{const r=await fetch(apiUrl('/api/content'),{method:'POST',headers:{'content-type':'application/json','x-admin-key':key},body:JSON.stringify(data)});if(!r.ok)throw new Error('保存失败');$('#msg').textContent='公开网页已更新 ✓'}catch(e){$('#msg').textContent=e.message||'保存失败'}};
